### ISSUE TITLE
Create token-gated membership page

### ISSUE THREAD

**Issue by briangershon** [Bittrees-Technology/bittrees-research-ui#14]
## Requirements

- Concept is generally mimicking https://www.berkshirehathaway.com/
- Also see [drawing](https://docs.google.com/drawings/d/1kdAmN2GiKeLxfyfVZa4J6iJOvQcG0Zy70azbzVPQD1Y/edit)

## Tasks

- [x] Create a token-gated page after user logs in to wallet
- [x] Creating the page (mainly links)
- [x] cache gate results
- [x] Add Vision Statement
- [x] Remove membership card
- [x] Hide links with no content -- grayed out
- [ ] member services at the top, and connect wallet button moved to the bottom, above logo. Spacing between different links in all directions.
- [ ] Remove cache if user logs out of of wallet

**Comment by briangershon** [comment]
Old issue, changes were already pushed into production branch. Closing.
